#!/bin/bash
run_acl_enum() {
    echo -e "${YELLOW}╔══════════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${YELLOW}║  PHASE 6: ACL Enumeration (Deferred to BloodHound)                   ║${NC}"
    echo -e "${YELLOW}╚══════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Create subdirectory
    mkdir -p acl

    # ACL path analysis (GenericAll/WriteDacl/WriteOwner) requires graph data and
    # nTSecurityDescriptor decoding, which is BloodHound's job. NOTE: this phase
    # runs BEFORE BloodHound collection (Phase 12), so checking for a zip here
    # would always miss. We point the operator at the BloodHound output that
    # Phase 12 produces instead.
    log_info "ACL path analysis is handled by BloodHound (Phase 12)"
    add_finding "INFO" "ACL Enumeration" \
        "ACL path analysis (GenericAll/WriteDacl/WriteOwner) is performed via BloodHound - see bloodhound/bloodyad_EXPLOITATION_GUIDE.txt generated by Phase 12" \
        "After the run: import bloodhound/*.zip into BloodHound, then Neo4j Query: MATCH p=(u:User)-[:GenericAll|WriteDacl|WriteOwner]->(t) RETURN p"

    SUCCESSFUL_CHECKS=$((SUCCESSFUL_CHECKS + 1))
}